package models

type CommandError struct {
	Code    int
	Message string
}

const (
	ERROR_INVALID_COMMAND = 1
	ERROR_INVALID_FORMAT  = 2
	ERROR_INTERNAL        = 3
	ERROR_QUEUE_NOTFOUND  = 4
	ERROR_JOB_NOTFOUND    = 5
	ERROR_QUEUE_DUPLICATE = 6
)

const (
	ERROR_INVALID_COMMAND_MSG = "INVALID_COMMAND"
	ERROR_INVALID_FORMAT_MSG  = "INVALID_FORMAT"
	ERROR_INTERNAL_MSG        = "INTERNAL_ERROR"
	ERROR_QUEUE_NOTFOUND_MSG  = "QUEUE_NOT_FOUND"
	ERROR_JOB_NOTFOUND_MSG    = "JOB_NOT_FOUND"
	ERROR_QUEUE_DUPLICATE_MSG = "QUEUE_DUPLICATE"
)
